name: PMTiles Metadata

on:
  workflow_dispatch:

jobs:
  metadata:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download pmtiles tool
        run: |
          wget https://github.com/protomaps/go-pmtiles/releases/download/v1.30.3/go-pmtiles_1.30.3_Linux_x86_64.tar.gz
          tar -xzf go-pmtiles_1.30.3_Linux_x86_64.tar.gz
          chmod +x go-pmtiles
      - name: Show Metadata
        run: |
          ./go-pmtiles show data/bogor.pmtiles

      - name: Show Header
        run: |
          ./go-pmtile inspect data/bogor.pmtiles
